# Generated by Django 4.2.17 on 2025-01-29 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_assistant', models.CharField(max_length=30)),
                ('id_vector_store', models.CharField(max_length=30)),
            ],
        ),
    ]
