# Generated by Django 4.2.17 on 2025-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testVectorStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
